### ISSUE TITLE
Better Installation Section

### ISSUE THREAD

**Issue by lfarah** [TBXark/TKRadarChart#1]
Hey, your library is really interesting.

The only problem I found was the `README.md`, which needs a better `Installation Section`.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily make the `Installation Section` better.
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by tbxark** [comment]
😄 Thanks, It is a really useful readme template , I organize my lib later.

**Comment by lfarah** [comment]
You're welcome. Glad you liked it! 😄
