### ISSUE TITLE
can not able to use diffrent colors :- colorOfLineForRadarChart

### ISSUE THREAD

**Issue by santhoshnextbrain** [TBXark/TKRadarChart#8]
Hi,

Is there option use multiple line colors can use?.

**Comment by tbxark** [comment]
I think you can modify this part of the code to achieve the UI you want.

https://github.com/TBXark/TKRadarChart/blob/f20b930d60e5b734aa8606682d5453778e333b99/TKRadarChart/TKRadarChart.swift#L240-L272
